COPY requirements-scraper.txt /var/task/requirements.txt
RUN pip install -r /var/task/requirements.txt
COPY lambda_function.py main.py /var/task/
COPY scrape/ /var/task/scrape/
COPY scripts/ /var/task/scripts/
RUN SUDO="$(command -v sudo > /dev/null && echo sudo || echo)" && $SUDO /var/task/scripts/update_cd.sh
RUN mkdir -p /opt/bin && ln -sf /opt/chrome/chrome /opt/bin/chromium

# Reset this to the normal AWS convention.
CMD ["lambda_function.lambda_handler"]
