# syntax = edrevo/dockerfile-plus
# TODO(jfdoming): remove once CfT supports arm64
FROM seleniarm/node-chromium:121.0-chromedriver-121.0@sha256:36ca0bf84b92665333c79aa7287764078d8e96e4b666e30b9eab527ae878aac8
RUN sudo apt-get update && \
    sudo apt-get install -y python3.11 python3-pip && \
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
    sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED
RUN sudo mkdir -p /opt/chrome && \
    sudo ln -s /usr/bin/chromium /opt/chrome/chrome && \
    sudo mkdir -p /var/task && \
    sudo chmod 777 /var/task
COPY requirements-dev.txt /requirements-dev.txt
RUN pip install -r /requirements-dev.txt

#INCLUDE+ Dockerfile.arm64.base
INCLUDE+ Dockerfile.common

# TODO(jfdoming): remove once CfT supports arm64
COPY local/lambda_entrypoint.py /
ENTRYPOINT ["python", "/lambda_entrypoint.py"]
